paths:
  /api/products:
    get:
      summary: Devuelve los productos
      tags:
        - Products
      responses:
        "200":
          description: Se obtinen los productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "400":
          descriptin: Error por db

components:
  schemas:
    Products:
      type: object
      properties:
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        thumbnail:
          type: array
          description: Imagen del producto
        code:
          type: string
          description: Código unico
        stock:
          type: number
          description: Stock del producto
        price:
          type: number
          description: Precio del producto
        status:
          type: boolean
          description: Activo o no activo
        category:
          type: string
          description: Categoria del producto
        owner:
          type: string
          description: Propietario del producto